  run-name: Deploy project to Azure
  on:
    workflow_call: 
    workflow_dispatch: 
    push:
      branches:
        - prod
    pull_request:
      branches:
        - prod

  env:
    AZURE_WEBAPP_NAME: relictify-api
    AZURE_WEBAPP_PACKAGE_PATH: '.'
  jobs:
    run-tests:
      uses: ./.github/workflows/test.yaml
      
    build-artifacts:
      needs: run-tests
      uses: ./.github/workflows/upload-build.yaml
      
    deploy-to-azure:
      runs-on: ubuntu-latest
      needs: build-artifacts
      environment:
        name: 'prod'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: latest-build

        - name: Deploy to Azure
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          env:
            APP_AUTH_KEY: ${{ secrets.APP_AUTH_KEY }}
      